### ISSUE TITLE
Need better documentation

### ISSUE THREAD

**Issue by ianfoo** [metaverse/truss#29] opened 2016-08-20 00:07 UTC
`README.md` needs to be fleshed out, or additional documentation needs to be added. It's a bit minimal now and doesn't do much in the way of introducing Truss, or have a Getting Started example to follow along with.

**Comment by zaquestion** [comment] 2016-08-21 23:29
Trying to create a service, some example protos in the project root would be to get one going.

Evidently there are some in the test directories: [add](https://github.com/TuneLab/go-truss/tree/master/truss/integration_tests/test_service_definitions/add)

**Comment by hasLeland** [comment] 2016-08-21 23:34
We should have some directions indicating the convention of putting the `.proto` file describing the microservice at the root of the folder where the (micro)service will live.

**Comment by hasLeland** [comment] 2016-08-21 23:36
There should be a link from a "Getting Started" section of the root README down to the more involved walkthrough found in `truss/README.md`.

**Comment by ianfoo** [comment] 2016-08-21 23:38
Yeah, as it stands right now, the root readme is the "website" for Truss,
so anything someone needs to know should be there or easily reachable from
there.

**Comment by hasAdamr** [comment] 2017-01-31 20:28
We have an [example protofile](https://github.com/TuneLab/go-truss/blob/master/_example/echo.proto) and a [tutorial](https://github.com/TuneLab/go-truss/blob/master/TUTORIAL.md) now thanks to @tuneliza. 

I am closing this as the issue is too general. A more specific issue to improve some aspect of the documentation could be opened.

**Closed as completed by hasAdamr** 2017-01-31 20:28 UTC
